"""Add additional fields to the Event model

Revision ID: 34bc9fbd5442
Revises: d9cb1f802965
Create Date: 2022-07-12 01:16:01.927227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34bc9fbd5442'
down_revision = 'd9cb1f802965'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('events', sa.Column('address', sa.String(length=124), nullable=False))
    op.add_column('events', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('events', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('events', sa.Column('playlist_link', sa.Text(), nullable=True))
    op.add_column('events', sa.Column('organizer_id', sa.Integer(), nullable=True))
    op.drop_index('ix_events_creator_id', table_name='events')
    op.create_index(op.f('ix_events_organizer_id'), 'events', ['organizer_id'], unique=False)
    op.drop_constraint('events_creator_id_fkey', 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'users', ['organizer_id'], ['id'])
    op.drop_column('events', 'creator_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key('events_creator_id_fkey', 'events', 'users', ['creator_id'], ['id'])
    op.drop_index(op.f('ix_events_organizer_id'), table_name='events')
    op.create_index('ix_events_creator_id', 'events', ['creator_id'], unique=False)
    op.drop_column('events', 'organizer_id')
    op.drop_column('events', 'playlist_link')
    op.drop_column('events', 'longitude')
    op.drop_column('events', 'latitude')
    op.drop_column('events', 'address')
    op.drop_column('events', 'description')
    # ### end Alembic commands ###
