"""Add is_organizer column to event_participants

Revision ID: 6d5616616969
Revises: 34bc9fbd5442
Create Date: 2022-07-15 00:21:05.752388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d5616616969'
down_revision = '34bc9fbd5442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_participants', sa.Column('is_organizer', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_participants', 'is_organizer')
    # ### end Alembic commands ###
