"""Add EventRole model

Revision ID: a81128971810
Revises: 6d5616616969
Create Date: 2022-07-20 22:43:32.252330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a81128971810'
down_revision = '6d5616616969'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_event_roles_default'), 'event_roles', ['default'], unique=False)
    op.add_column('event_participants', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('event_participants', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'event_participants', 'event_roles', ['role_id'], ['id'])
    op.drop_column('event_participants', 'is_organizer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_participants', sa.Column('is_organizer', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'event_participants', type_='foreignkey')
    op.drop_column('event_participants', 'role_id')
    op.drop_column('event_participants', 'id')
    op.drop_index(op.f('ix_event_roles_default'), table_name='event_roles')
    op.drop_table('event_roles')
    # ### end Alembic commands ###
