"""Add tokens Table

Revision ID: ab5caefecee6
Revises: ffa1105007c8
Create Date: 2022-07-07 20:48:15.300611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab5caefecee6'
down_revision = 'ffa1105007c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.String(length=64), nullable=False),
    sa.Column('token_expiration', sa.DateTime(), nullable=False),
    sa.Column('token_type', sa.String(length=10), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_token_id'), 'tokens', ['token_id'], unique=False)
    op.create_index(op.f('ix_tokens_token_type'), 'tokens', ['token_type'], unique=False)
    op.create_index(op.f('ix_tokens_user_id'), 'tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tokens_user_id'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_token_type'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_token_id'), table_name='tokens')
    op.drop_table('tokens')
    # ### end Alembic commands ###
