"""Add User foreign key to the Event model

Revision ID: d9cb1f802965
Revises: a917a08d3bd3
Create Date: 2022-07-11 21:24:18.834907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9cb1f802965'
down_revision = 'a917a08d3bd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_events_creator_id'), 'events', ['creator_id'], unique=False)
    op.create_foreign_key(None, 'events', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_index(op.f('ix_events_creator_id'), table_name='events')
    op.drop_column('events', 'creator_id')
    # ### end Alembic commands ###
